apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  namespace: iris-pipeline-example # Must match the namespace where your pipeline runs
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: YOUR_BASE64_ENCODED_DOCKER_CONFIG_JSON # Replace this with your base64 encoded ~/.docker/config.json

# To generate YOUR_BASE64_ENCODED_DOCKER_CONFIG_JSON, run:
# cat ~/.docker/config.json | base64 -w 0
